<?php
require __DIR__.'/vendor/autoload.php';
require 'app.php';need();if(!admin()){http_response_code(403);exit('Admins only');}
use Dompdf\Dompdf;
use Dompdf\Options;

$id=(int)($_GET['election']??0);
$election=q('SELECT title,status FROM elections WHERE id=?',[$id])->fetch();
if(!$election||$election['status']!=='closed'){http_response_code(404);exit('Reports are available for closed elections only.');}
$rows=q('SELECT c.name,o.name organization_name,COUNT(b.id) votes FROM candidates c LEFT JOIN organizations o ON o.id=c.organization_id LEFT JOIN ballots b ON b.candidate_id=c.id WHERE c.election_id=? GROUP BY c.id,o.id ORDER BY votes DESC,c.name',[$id])->fetchAll();
$total=array_sum(array_column($rows,'votes'));
$html='<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:34px 38px}body{font-family:"DejaVu Sans",sans-serif;color:#20312c;font-size:10px;line-height:1.45}
.banner{background:#0b6e4f;color:#fff;padding:22px 24px}.brand{font-size:10px;font-weight:bold;text-transform:uppercase}.banner h1{font-size:22px;margin:12px 0 4px}.subtitle{font-size:11px;color:#e5f3ee}
.meta{width:100%;margin:18px 0 12px;border-collapse:collapse}.meta td{width:50%;padding:10px 12px;background:#f1f5f3;border:1px solid #dce5e0}.label{font-size:8px;color:#62736c;text-transform:uppercase}.value{font-size:12px;font-weight:bold;margin-top:3px}
.summary{margin:12px 0 22px;padding:14px 16px;background:#e6f2ed;border-left:4px solid #0b6e4f}.summary-label{font-size:9px;color:#52665d;text-transform:uppercase}.summary-value{font-size:23px;font-weight:bold;color:#0b6e4f}
h2{font-size:13px;margin:0 0 9px}.results{width:100%;border-collapse:collapse}.results th{background:#153e32;color:#fff;text-align:left;padding:9px 8px;font-size:9px}.results td{padding:9px 8px;border-bottom:1px solid #dce5e0}.results tr:nth-child(even) td{background:#f7f9f8}.num{text-align:right;white-space:nowrap}.rank{color:#718178;width:28px}.member{font-weight:bold}.organization{color:#66766f;font-size:9px;margin-top:2px}.total td{background:#e6f2ed!important;font-weight:bold;border-top:2px solid #0b6e4f}.foot{margin-top:20px;padding-top:8px;border-top:1px solid #dce5e0;color:#77857e;font-size:8px}
</style></head><body>';
$html.='<div class="banner"><div class="brand">E-Voting · Official Results</div><h1>'.e($election['title']).'</h1><div class="subtitle">Election results report</div></div>';
$html.='<table class="meta"><tr><td><div class="label">Election status</div><div class="value">Closed</div></td><td><div class="label">Generated</div><div class="value">'.e(date('F j, Y')).'</div></td></tr></table>';
$html.='<div class="summary"><div class="summary-label">Total votes recorded</div><div class="summary-value">'.number_format($total).'</div></div>';
$html.='<h2>Final tally</h2><table class="results"><thead><tr><th class="rank">#</th><th>Member / candidate</th><th>Organization</th><th class="num">Votes</th><th class="num">Share</th></tr></thead><tbody>';
if($rows){
 foreach($rows as $index=>$row){
  $percentage=$total?round($row['votes']*100/$total,1):0;
  $html.='<tr><td class="rank">'.($index+1).'</td><td class="member">'.e($row['name']).'</td><td class="organization">'.e($row['organization_name']??'No organization').'</td><td class="num">'.number_format($row['votes']).'</td><td class="num">'.$percentage.'%</td></tr>';
 }
}else $html.='<tr><td colspan="5">No candidates were recorded for this election.</td></tr>';
$html.='<tr class="total"><td colspan="3">TOTAL VOTES</td><td class="num">'.number_format($total).'</td><td class="num">'.($total?'100':'0').'%</td></tr></tbody></table>';
$html.='<div class="foot">Generated by E-Voting · This report reflects the final tally at the time of download.</div></body></html>';

$options=new Options();
$options->setDefaultFont('DejaVu Sans');
$options->setIsRemoteEnabled(false);
$dompdf=new Dompdf($options);
$dompdf->loadHtml($html,'UTF-8');
$dompdf->setPaper('A4','portrait');
$dompdf->render();
$dompdf->stream('election-report-'.$id.'.pdf',['Attachment'=>true]);